### ISSUE TITLE
NCP서버 CICD 구축 및 index페이지 연결

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/my-seat-dang#1]
# 🌈 Success criteria
1. Github 액션을 사용하여 NCP 클라우드의 CI/CD dev-ops 구축

## 🎈 추가 자료

# 👷To-do
- [ ] git.ignore 작성
- [ ] 프로젝트 생성 및 index 작성
- [ ] NCP 서버 생성
- [ ] 서버에 docker 설치
- [ ] docker hub 페이지 생성
- [ ] Github Action 구축
- [ ] 테스트

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
