### ISSUE TITLE
[웨이팅] 일반회원은 나의 웨이팅 현황을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#102]
# 🌈 Success criteria
나의 웨이팅 현황을 조회
# 👷To-do
- [ ] 나의 웨이팅 목록을 조회할 수 있습니다.
- [ ] 웨이팅 현황 페이지에는 예상 대기시간, 총 대기인원, 나의 대기번호를 조회할 수 있습니다.
- [ ] 새로고침버튼을 누를 시 누르는 시각기준으로 현재 자신의 순서를 불러옵니다.
- [ ] 웨이팅 현황 페이지 구현

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
