### ISSUE TITLE
[결제] 사용자는 결제를 할 수 있습니다.

### ISSUE THREAD

**Issue by i-Veni-Vidi-Vici** [ssg-java3-240304/my-seat-dang#108]
# 🌈 Success criteria

# 👷To-do
- [x] 결제(준비)
- [x] 결제(승인)
    - [x] 결제(승인 성공)
    - [x] 결제(승인 실패)
- [x] secret key 설정

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
