### ISSUE TITLE
일반사용자는 OAUTH로 네이버로그인을 할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#159]
# 🌈 Success criteria

일반사용자는 OAUTH로 네이버로그인을 할 수 있습니다.

# 👷To-do
- [x] 네이버 API 설정 완료
- [x] OAUTH 환경설정 (doker_image.yml 수정,gradle, application.yaml에 추가)
- [x] 로그인성공
- [x] 로그아웃성공 
- [x] 배포시 링크 바꾸기

# 👓 Review
1. 
![image](https://github.com/user-attachments/assets/0be4cca3-226e-40a0-b72b-8bab0d842a4c)

2. Oauth API 설정 Actions secrets and variables
![image](https://github.com/user-attachments/assets/1a84c5a9-e896-43ea-a703-5ed6056f68cf)

3. 배포시 링크 변경 (배포주소로)
https://developers.naver.com/products/login/api/api.md

**Comment by nnieun** [comment]
![image](https://github.com/user-attachments/assets/5fd046ab-2a0a-4ada-8ce7-df9f7223cc5c)
혼자 붕떠있어서 고민이다
