### ISSUE TITLE
[학습] 사용할 API 테스트하기

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#17]
# 🌈 Success criteria
1. 나경- ai dalle api 이미지생성을 완료합니다.

# 👷To-do
- [ ] ai dalle api을 위한 환경설정(Repository secrets) 설정을 완료합니다.
- [ ] ai dalle api을 위한 환경설정(gradle, yaml) 설정을 완료합니다.
- [ ] ai 이미지 생성을 완료합니다.

# 👓 Review
1. 
![image](https://github.com/user-attachments/assets/fbb4cf5c-bcd2-4761-adb5-261e9a57784a)
2. 
![image](https://github.com/user-attachments/assets/17efacb3-bc1e-44b4-9354-4e832025a50b)
