### ISSUE TITLE
[결제] 결제 요청/승인 엔티티 변경 

### ISSUE THREAD

**Issue by i-Veni-Vidi-Vici** [ssg-java3-240304/my-seat-dang#198]
# 🌈 Success criteria
- shopId 추가
- 키 tid ->  partnerOrderId로 변경

# 👷To-do
- [x] 결제 요청/승인 엔티티 변경
- [x] 관련된 controller 변경
- [x] 관련된  service 변경
- [x] 관련된  repository 변경

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
