### ISSUE TITLE
[메뉴] 메뉴 서비스 구현 및 테스트 하기

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/my-seat-dang#202]
# 🌈 Success criteria
- 메뉴 등록, 조회, 수정, 삭제를 수행하는 서비스를 구현합니다
- MenuQueryService는 메뉴 조회하는 Get 요청 처리 서비스를 제공합니다
- MenuCommandService 메뉴 등록, 수정, 삭제를 하는 Post 요청 처리 서비스를 제공합니다

# 👷To-do
- [ ] MenuQueryService - 메뉴 한 건 조회 구현 및 테스트
- [ ] MenuQueryService - 매장번호로 특정 매장에 속한 모든 메뉴 조회 구현 및 테스트
- [ ] MenuQueryService - 매장번호 + 메뉴이름으로 특정 매장에 속한 모든 메뉴 조회 구현 및 테스트
- [ ] MenuCommandService - 메뉴 등록 구현 및 테스트
- [ ] MenuCommandService - 메뉴 수정 구현 및 테스트
- [ ] MenuCommandService - 메뉴 삭제 구현 및 테스트

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
