### ISSUE TITLE
[1대1문의] 점주는 고객이 요청한 상품에 따른 결제를 요청할 수 있습니다.

### ISSUE THREAD

**Issue by yongjun98** [ssg-java3-240304/my-seat-dang#245]
# 🌈 Success criteria

# 👷To-do
- [ ] 결제정보를 입력받을 필드값 추가 
- [ ] 입력받은 결제정보를 몽고에 저장 
- [ ] 새로고침시 그대로 읽어오도록 sse 설정 

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
