### ISSUE TITLE
[매장정보] 일반 회원은 매장 상세 정보를 조회 할 수 있습니다.

### ISSUE THREAD

**Issue by jeongeun1** [ssg-java3-240304/my-seat-dang#28]
# 🌈 Success criteria
1. 일반 회원은 매장 목록에서 한 매장을 클릭하면 상세 정보를 조회할 수 있습니다.
2. 매장 상세 페이지는 아래 정보를 포함합니다.
- 홈 : 매장 사진, 매장명, 별점, 리뷰(간략), 매장 소개, 영업시간, 위치, 전화번호, 공지사항
- 메뉴 : 메뉴판, 메뉴, 가격, 메뉴 이미지
- 리뷰
- 예약하기/웨이팅하기 or 예약중/웨이팅중
2. 사용자는 현재 조회 중인 매장을 보고 있는 사용자가 몇명인지 조회할 수 있습니다

# 👷To-do
- [ ] 매장 상세 페이지에서 홈, 메뉴, 리뷰 탭을 조회 할 수 있습니다.
- [ ] 일반 베이커리 가게에서는 웨이팅하기, 제작케이크 가게에서는 예약하기 버튼을 사용 할 수 있습니다.
- [ ] 현재 조회 중인 사용자의 수를 확인할 수 있습니다.

# 👓 Review
