### ISSUE TITLE
[회원] 일반회원은 ai 케이크시안생성을 할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#281]
# 🌈 Success criteria
케이크 시안 생성을 할 수 있습니다.
# 👷To-do
- [x] 환경설정
- [x] 케이크 시안 이미지 생성 테스트
- [x] NCP 클라우드에 업로드 완료
- [x] DB에 URL 저장 완료
- [x] #284
# 👓 Review
1. 환경설정
2. 케이크시안 이미지 생성 테스트 완료
3. NCP 클라우드에 업로드 완료
4. DB URL 및 횟수 차감
![image](https://github.com/user-attachments/assets/52e6efdb-862b-41b6-9854-a319dc5f7806)
![image](https://github.com/user-attachments/assets/839df019-0618-4e8b-8c82-ba879f63e017)
![image](https://github.com/user-attachments/assets/f6c4694c-fba6-48cd-ab2b-322e60b2d395)
