### ISSUE TITLE
매장 검색 결과 레이아웃 개선

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/my-seat-dang#342]
# 🌈 Success criteria
- 매장 검색 레이아웃이 가독성이 떨어진다는 피드백을 받고 있습니다.
- 좀 더 직관적인 사용자 레이아웃으로 변경합니다

# 👷To-do
- [x] 탭을 사용하여 매장 타입을 직관적으로 분리
- [x] 이미지 매장 좌상단에 매장 유형을 표시
- [x] 폰트를 키워 가독성 향상
- [x] 지도의 너비를 제한

# 👓 Review
1. 이전 화면
![image](https://github.com/user-attachments/assets/14c1c5e1-fedf-4845-be8b-2c5dc677e876)

2. 개선된 화면
![image](https://github.com/user-attachments/assets/dd70439a-e35c-489d-a528-54ffe166d28e)
