### ISSUE TITLE
[Index] 랜딩페이지 구현

### ISSUE THREAD

**Issue by jeongeun1** [ssg-java3-240304/my-seat-dang#344]
# 🌈 Success criteria
1. 검색 기능 외 카테고리별 조회, AI시안 생성 바로가기 배너를 만듭니다.
2. 상단 navigation바를 프로젝트 기능에 맞게 수정합니다.

# 👷To-do
- [x] 카테고리별 조회, AI시안 생성 바로가기 배너 만들기
- [ ] 각 카테고리에 적합한 링크 연결
- [ ] AI시안 생성 바로가기 링크 연결
- [ ] nav 수정

# 👓 Review
