### ISSUE TITLE
[1대1 문의] 일반회원은 점주에게 custom 케잌을 위한 1대1 문의 채팅을 진행할 수 있습니다.

### ISSUE THREAD

**Issue by yongjun98** [ssg-java3-240304/my-seat-dang#46]
# 🌈 Success criteria

# 👷To-do
- [ ] 1.  일반회원은 매장 1:1문의 기능을 클릭하여 판매자와 DM을 할 수 있습니다
- [ ] 2. 일반회원은 점주에게 텍스트와 이미지 및 파일을 전송할 수 있습니다.
- [ ] 3. 일반회원은 점주와의 채팅을 통해 결제를 진행 할 수 있습니다. 

# 👓 Review
1.
