### ISSUE TITLE
[검색-2] 지도에 PIN 표시하기

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/my-seat-dang#56]
# 🌈 Success criteria
- 검색한 매장 목록을 지도에 표시하고 클릭시 매장 정보를 출력하는 Mark를 생성합니다

# 👷To-do
- [ ] 지도에 위도와 경도 정보로 Mark를 표시합니다
- [ ] 주소 정보로 지도에 Mark를 표시합니다
- [ ] 매장정보를 연동하여 여러개의 Mark를 지도에 표시합니다

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
