### ISSUE TITLE
[통계] 점주는 대시보드를 조회할 수 있습니다

### ISSUE THREAD

**Issue by CstoneKu** [ssg-java3-240304/my-seat-dang#61]
# 🌈 Success criteria
- 점주는 대시보드를 사용하여 매장 운영에 도움이 되는 통계 정보를 조회할 수 있습니다
- 일간 웨이팅 건수
- 주간 웨이팅 건수
- 요일별 웨이팅 건수
- 한 팀당 평균 웨이팅 시간
- 일간 / 주간 예약 건수
- 일간 / 주간 예약 결제 매출액

# 👷To-do
- [ ] [통계] 일간 웨이팅 건수 구현
- [ ] [통계] 주간 웨이팅 건수 구현
- [ ] [통계] 요일별 웨이팅 건수 구현
- [ ] [통계] 한 팀당 평균 웨이팅 시간 구현
- [ ] [통계] 일간 / 주간 예약 건수 구현
- [ ] [통계] 일간 / 주간 예약 결제 매출액 구현

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
