### ISSUE TITLE
[회원관리] 점주회원은 회원가입을 할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#63]
# 🌈 Success criteria
점주회원 회원가입을 할 수 있습니다.
점주회원은 점주 로그인 페이지에서 아이디,비밀번호를 입력하여 로그인 할 수 있습니다.
# 👷To-do
- [ ] 이름, 닉네임,비밀번호,휴대전화번호,이메일을 입력할 수 있습니다.
- [ ] 사업자등록증,영업신고증,입금통장사본,로고이미지를 입력 할 수 있습니다. (이미지파일업로드)
- [ ] 일반회원은 회원가입할 때이메일 중복인증을 해야합니다.
- [ ] 비밀번호는 영문,숫자,특수문자를 혼합하여 10자 이상으로 설정해야합니다.
- [ ] 일반회원은 회원가입할 때 휴대폰 인증을 해야합니다.
- [ ] 점주회원은 관리자의 승인을 받기전까지 회원가입이 이루어지지 않습니다.
- [ ] 점주 회원가입 페이지 구현
- [ ] 점주 로그인 페이지 구현

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
