### ISSUE TITLE
[회원관리] 일반회원은 자신의 정보를 수정 할 수 있습니다.

### ISSUE THREAD

**Issue by nnieun** [ssg-java3-240304/my-seat-dang#90]
# 🌈 Success criteria
일반회원은 마이페이지에서 자신의 정보를 수정 할 수 있습니다.
# 👷To-do
- [x] 일반 사용자는 닉네임을 수정할 수 있습니다.
- [x] 일반 사용자는 성별을 수정할 수 있습니다.
- [x] 일반사용자는 생일을 수정할 수 있습니다.
- [x] 일반 사용자는 대표 이미지를 수정할 수있습니다.
- [x]  일반 사용자는 비밀번호를 변경할 수 있습니다.
- [x] #241

# 👓 Review
1. <작업진행 상황을 스크린샷등 각종 이미지등으로 적극적으로 작성하고, 코드리뷰때 전달합니다.>
